config/routes.rb
Rails.application.routes.draw do
	namespace :admin do
	  	devise_for :users, skip: :all
	  	devise_for :users, controllers: { sessions: 'admin/users/sessions' }
	  	get 'products', to: 'products#index', as: 'products'
	  	get 'products/new', to: 'products#new', as: 'new_products'
	  	get 'products/:id', to: 'products#show', as: 'product'
	  	get 'products/:id/edit', to: 'products#edit', as: 'edit_products'
	  	put '/products/:id', to: "products#update", as: 'update_products'
	  	delete '/products/:id', to: 'products#destroy', as: 'destroy_products'
	  	post '/products', to: "products#create", as: 'create_products'

	  	get 'categories', to: 'categories#index', as: 'categories'
	  	get 'categories/new', to: 'categories#new', as: 'new_categories'
	  	get 'categories/:id', to: 'categories#show', as: 'category'
	  	get 'categories/:id/edit', to: 'categories#edit', as: 'edit_categories'
	  	put '/categories/:id', to: "categories#update", as: 'update_categories'
	  	delete '/categories/:id', to: 'categories#destroy', as: 'destroy_categories'
	  	post '/categories', to: "categories#create", as: 'create_categories'
		root to: 'products#index'	

		get 'users', to: 'users#index', as: 'users'
	  	get 'users/new', to: 'users#new', as: 'new_users'
	  	get 'users/:id', to: 'users#show', as: 'user'
	  	get 'users/:id/edit', to: 'users#edit', as: 'edit_users'
	  	put '/users/:id', to: "users#update", as: 'update_users'
	  	delete '/users/:id', to: 'users#destroy', as: 'destroy_users'
	  	post '/users', to: "users#create", as: 'create_users'

	  	get 'posts', to: 'posts#index', as: 'posts'
	  	get 'posts/new', to: 'posts#new', as: 'new_posts'
	  	get 'posts/:id', to: 'posts#show', as: 'post'
	  	get 'posts/:id/edit', to: 'posts#edit', as: 'edit_posts'
	  	put '/posts/:id', to: "posts#update", as: 'update_posts'
	  	delete '/posts/:id', to: 'posts#destroy', as: 'destroy_posts'
	  	post '/posts', to: "posts#create", as: 'create_posts'

	  	get 'comments', to: 'comments#index', as: 'comments'
	  	get 'comments/new', to: 'comments#new', as: 'new_comments'
	  	get 'comments/:id', to: 'comments#show', as: 'comment'
	  	get 'comments/:id/edit', to: 'comments#edit', as: 'edit_comments'
	  	put '/comments/:id', to: "comments#update", as: 'update_comments'
	  	delete '/comments/:id', to: 'comments#destroy', as: 'destroy_comments'
	  	post '/comments', to: "comments#create", as: 'create_comments'

	  	get 'replies', to: 'replies#index', as: 'replies'
	  	get 'replies/new', to: 'replies#new', as: 'new_replies'
	  	get 'replies/:id', to: 'replies#show', as: 'reply'
	  	get 'replies/:id/edit', to: 'replies#edit', as: 'edit_replies'
	  	put '/replies/:id', to: "replies#update", as: 'update_replies'
	  	delete '/replies/:id', to: 'replies#destroy', as: 'destroy_replies'
	  	post '/replies', to: "replies#create", as: 'create_replies'
	end
	devise_for :users
	resources :products
	resources :users
	post '/create_comment', to: 'products#create_comment'
	get '/get_comment', to: 'products#get_comment'

	post '/create_reply', to: 'products#create_reply'
	get '/get_reply', to: 'products#get_reply'

	get '/search',to: 'products#search', :as => 'search_products'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root to: 'products#index'
	get'/show', to:'categories#show' , as: 'category'
end
	

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments,dependent: :destroy
  belongs_to :product
  validates_uniqueness_of :product_id
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController
	before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.where(["name LIKE ?","%#{params[:search]}%"])
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
    @products = Product.all
    @users = User.all
  end

  # GET /posts/1/edit
  def edit
  	@products = Product.all
    @users = User.all
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
     
      if @post.save
         redirect_to admin_posts_path(@post)
      else
        render :new , errors: @post.errors.messages.slice

    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
      if @post.update(post_params)
        redirect_to admin_posts_path(@post)
      else
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
     redirect_to admin_posts_path(@post)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :content, :product_id, :user_id)
    end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/posts/_form.html.erb
<%= form_with(scope: :post, url:  admin_update_posts_path, method: :put, local: true) do |form| %>
   <div class="form-group" style="margin-left: 20%; margin-right: 20%;">
     <%= form.label :name %>
     <%= form.text_field :name, id: :post_name, class:'form-control'%>
   </div>

   <div class="form-group" style="margin-left: 20%; margin-right: 20%;">
     <%= form.label :content%>
     <%= form.text_area :content, id: :post_content,  class:'form-control'%>
   </div>
   <div class="form-group" style="margin-left: 20%; margin-right: 20%;">
     <%= form.label :product_id %>
     <%= form.select(:product_id, @products.map{|f| [f.name, f.id]}, {}, { :class => 'form-control' })%>
   </div>
    <div class="form-group" style="margin-left: 20%; margin-right: 20%;">
     <%= form.label :user_id %>
     <%= form.select(:user_id, @users.map{|f| [f.name, f.id]}, {}, { :class => 'form-control' })%>
   </div>
   <div class="actions" style="margin-left: 20%; margin-right: 20%;">
     <%= form.submit %>
   </div>
 <% end %>

app/views/admin/posts/edit.html.erb
<h1 style="margin-left: 20%; margin-right: 20%;color: #ff0000">Chỉnh sửa bài đăng</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', admin_post_path(@post) %> |
<%= link_to 'Trở lại',  admin_posts_path %>

app/views/admin/posts/index.html.erb
<p id="notice"><%= notice %></p>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">ADMIN</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Trang chủ</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" <%= link_to "Sản Phẩm ",admin_products_path%></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" <%= link_to "Loại sản phẩm ",admin_categories_path%></a>
      </li>
      <li class="nav-item">
        <a class="nav-link"<%= link_to "Tài khoản người dùng",admin_users_path%></a>
      </li>
        <li class="nav-item">
        <a class="nav-link" <%= link_to "Bài Đăng",admin_posts_path%></a>
      </li>
       <li class="nav-item">
        <a class="nav-link" <%= link_to "Bình luận",admin_comments_path%></a>
      </li>
        <li class="nav-item">
        <a class="nav-link" <%= link_to "Trả lời bình luận",admin_replies_path %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link"<%= link_to('Đăng xuất', destroy_admin_user_session_path, method: :delete , data: { confirm: 'Are you sure?' }) %> </a>
      </li>
    </ul>
           <%= form_tag(admin_posts_path, :method => "get",   
          class: 'navbar-form navbar-left') do %>  
             <div class="input-group">  
              <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>  
            <div class="input-group-btn" style="margin-right: 10%; height: 20%; width: 20%">  
              <%= button_tag "Search", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>  
          </div>  
  </div>  
<% end %>
  </div>
</nav>
<th class=""><%= link_to 'Bài Đăng', admin_new_posts_path %>   </th>
  <table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">Mã bài đăng</th>
      <th scope="col">Tên bài đăng </th>
      <th scope="col">Nội dung </th>
      <th scope="col">Sản phẩm </th>
      <th scope="col">Người đăng</th>
      < <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post|%>
    <tr>
      <td><%= post.id %></td>
      <td><%= post.name %></td>
      <td><%= post.content %></td> 
      <td><%= post.product.name%></td>
      <td><%= post.user.name%></td>
      <td><%= link_to 'Sửa ', admin_edit_posts_path(post.id)%></td>
      <td><%= link_to 'Xóa',  admin_destroy_posts_path(post.id), method: :delete, data: { confirm: 'Bạn chắc chắn muốn xóa chứ?' } %></td>
    </tr>
     <% end %>
  </tbody>
</table>
<%= link_to 'Trở lại', admin_products_path %>

app/views/admin/posts/new.html.erb
<%= form_with(scope: :post, url:  admin_create_posts_path, local: true) do |form| %>
   <div class="form-group" style="margin-left: 20%; margin-right: 20%;">
     <%= form.label :name %>
     <%= form.text_field :name, id: :post_name, class:'form-control'%>
   </div>

   <div class="form-group" style="margin-left: 20%; margin-right: 20%;">
     <%= form.label :content%>
     <%= form.text_area :content, id: :post_content,  class:'form-control'%>
   </div>
   <div class="form-group" style="margin-left: 20%; margin-right: 20%;">
     <%= form.label :product_id %>
     <%= form.select(:product_id, @products.map{|f| [f.name, f.id]}, {}, { :class => 'form-control' })%>
   </div>
    <div class="form-group" style="margin-left: 20%; margin-right: 20%;">
     <%= form.label :user_id %>
     <%= form.select(:user_id, @users.map{|f| [f.name, f.id]}, {}, { :class => 'form-control' })%>
   </div>
   <div class="actions" style="margin-left: 20%; margin-right: 20%;">
     <%= form.submit %>
   </div>
 <% end %>
 <%= link_to 'Trở lại', admin_posts_path %>