config/routes.rb
Rails.application.routes.draw do
	namespace :admin do
	  	devise_for :users, skip: :all
	  	devise_for :users, controllers: { sessions: 'admin/users/sessions' }
	  	get 'products', to: 'products#index', as: 'products'
	  	get 'products/new', to: 'products#new', as: 'new_products'
	  	get 'products/:id', to: 'products#show', as: 'product'
	  	get 'products/:id/edit', to: 'products#edit', as: 'edit_products'
	  	put '/products/:id', to: "products#update", as: 'update_products'
	  	delete '/products/:id', to: 'products#destroy', as: 'destroy_products'
	  	post '/products', to: "products#create", as: 'create_products'

	  	get 'categories', to: 'categories#index', as: 'categories'
	  	get 'categories/new', to: 'categories#new', as: 'new_categories'
	  	get 'categories/:id', to: 'categories#show', as: 'category'
	  	get 'categories/:id/edit', to: 'categories#edit', as: 'edit_categories'
	  	put '/categories/:id', to: "categories#update", as: 'update_categories'
	  	delete '/categories/:id', to: 'categories#destroy', as: 'destroy_categories'
	  	post '/categories', to: "categories#create", as: 'create_categories'
		root to: 'products#index'	

		get 'users', to: 'users#index', as: 'users'
	  	get 'users/new', to: 'users#new', as: 'new_users'
	  	get 'users/:id', to: 'users#show', as: 'user'
	  	get 'users/:id/edit', to: 'users#edit', as: 'edit_users'
	  	put '/users/:id', to: "users#update", as: 'update_users'
	  	delete '/users/:id', to: 'users#destroy', as: 'destroy_users'
	  	post '/users', to: "users#create", as: 'create_users'

	  	get 'posts', to: 'posts#index', as: 'posts'
	  	get 'posts/new', to: 'posts#new', as: 'new_posts'
	  	get 'posts/:id', to: 'posts#show', as: 'post'
	  	get 'posts/:id/edit', to: 'posts#edit', as: 'edit_posts'
	  	put '/posts/:id', to: "posts#update", as: 'update_posts'
	  	delete '/posts/:id', to: 'posts#destroy', as: 'destroy_posts'
	  	post '/posts', to: "posts#create", as: 'create_posts'

	  	get 'comments', to: 'comments#index', as: 'comments'
	  	get 'comments/new', to: 'comments#new', as: 'new_comments'
	  	get 'comments/:id', to: 'comments#show', as: 'comment'
	  	get 'comments/:id/edit', to: 'comments#edit', as: 'edit_comments'
	  	put '/comments/:id', to: "comments#update", as: 'update_comments'
	  	delete '/comments/:id', to: 'comments#destroy', as: 'destroy_comments'
	  	post '/comments', to: "comments#create", as: 'create_comments'

	  	get 'replies', to: 'replies#index', as: 'replies'
	  	get 'replies/new', to: 'replies#new', as: 'new_replies'
	  	get 'replies/:id', to: 'replies#show', as: 'reply'
	  	get 'replies/:id/edit', to: 'replies#edit', as: 'edit_replies'
	  	put '/replies/:id', to: "replies#update", as: 'update_replies'
	  	delete '/replies/:id', to: 'replies#destroy', as: 'destroy_replies'
	  	post '/replies', to: "replies#create", as: 'create_replies'
	end
	devise_for :users
	resources :products
	resources :users
	post '/create_comment', to: 'products#create_comment'
	get '/get_comment', to: 'products#get_comment'

	post '/create_reply', to: 'products#create_reply'
	get '/get_reply', to: 'products#get_reply'

	get '/search',to: 'products#search', :as => 'search_products'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root to: 'products#index'
	get'/show', to:'categories#show' , as: 'category'
end
	

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category
	has_many :evaluates
	has_one :post,dependent: :destroy
	validates :price,presence: true, numericality:  { greater_than_or_equal_to: 0 }
	validates :description, presence: true, length:{ minimum: 2 }
	validates :name ,presence: true, length:{ minimum: 5 }
    has_attached_file :image, styles: { medium: "500x500>", thumb: "100x100>" }, default_url: ""
    # validates_attachment :image, content_type: ["image/jpeg", "image/gif", "image/png"]
	validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }


	def self.search(search)
		where("name LIKE ?", "%#{search}%")
	end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
    before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @categories = Category.all
    #@products = Product.all 
   @products = Product.where(["name LIKE ?","%#{params[:search]}%"])
  end
  # def search
  #   @products = Product.all
  #   if params[:search].blank?  
  #     redirect_to admin_products_path(@product)
  #   else
  #     @parameter = params[:search].downcase  
  #     @products = Product.all.where("lower(name) LIKE :search", search: @parameter)  
  #   end  
  # end

  # GET /products/1
  # GET /products/1.json
  def show
    @categories = Category.all
  end

  # GET /products/new
  def new
    @product = Product.new
    @categories = Category.all
  end

  # GET /products/1/edit
  def edit
    @categories = Category.all
  end

  # POST /products
  # POST /products.json
  def create
      @product = Product.new(product_params)
        if @product.save
          redirect_to  admin_products_path(@product)
        else
          render :new , errors: @product.errors.messages.slice
      end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
      if @product.update(product_params)
        redirect_to admin_products_path(@product)
      else
        render :edit 
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    redirect_to admin_root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :description, :category_id, :image)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	skip_before_action :verify_authenticity_token, only: :create_comment
	# before_action :authenticate_user! , only: :create_comment
	def index
		

		#@products = Product.paginate(page: params[:page],per_page: 8)
		@products = Product.where(["name LIKE ?","%#{params[:search]}%"])
		#@products = Product.search(params[:product])
  		#@serach = @product.result.includes(:articles).page(params[:page])
	end

	def show
		@product = Product.find(params[:id])
	def create_comment
		if current_user.nil?
			render :json => {success: false}
		else
			comment = Comment.new(user_id: current_user.id, post_id: params[:post_id], content: params[:content])
			render :json => {success: comment.save}
		end
	end

	def get_comment
		number = params[:number] || 0
		obj = []
		comments = Comment.where(post_id: params[:post_id]).last(number)
		comments.each do |f|
			obj << {content: f.content, email: f.user.email}
		end
		render :json => {comments: obj}
	end


	def create_reply
		if current_user.nil?
			render :json => {success: false}
		else
			reply = Reply.new(user_id: current_user.id, comment_id: params[:comment_id], content: params[:content])
			render :json => {success: reply.save}
		end
	end
	def get_reply
		number = params[:number] || 0
		obj = []
		replies = Reply.where(comment_id: params[:comment_id]).last(number)
		replies.each do |f|
			obj << {content: f.content, email: f.user.email}
		end
		render :json => {replies: obj}
	end
end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
 <%= form_with(scope: :product, url: admin_update_products_path, method: :put, local: true) do |form| %>

   <% if product.errors.any? %>
     <div id="error_explanation">
       <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

       <ul>
       <% product.errors.full_messages.each do |message| %>
         <li><%= message %></li>
       <% end %>
       </ul>
     </div>
   <% end %>

   <div class="form-group" style="margin-left: 20%; margin-right: 20%">
     <%= form.label :name %>
     <%= form.text_field :name, id: :product_name, class:'form-control'%>
   </div>

   <div class="form-group" style="margin-left: 20%; margin-right: 20%">
     <%= form.label :price %>
     <%= form.text_area :price, id: :product_price,  class:'form-control'%>
   </div>
    <div class="form-group" style="margin-left: 20%; margin-right: 20%">
     <%= form.label :description %>
     <%= form.text_area :description, id: :product_description, class:'form-control' %>
   </div>

   <div class="form-group" style="margin-left: 20%; margin-right: 20%">
     <%= form.label :category_id %>
     <%= form.select(:category_id, @categories.map{|f| [f.name, f.id]}, {}, { :class => 'form-control' })%>
   </div>

   <div class="form-group" style="margin-left: 20%; margin-right: 20%">
     <%= form.label :image %>
     <%= form.file_field :image, id: :product_image,  class:'form-control'%>
   </div>
   <div class="actions" style="margin-left: 20%; margin-right: 20%">
     <%= form.submit %>
   </div>
 <% end %>

app/views/admin/products/edit.html.erb
<h1 style="margin-left: 20%; margin-right: 20%; color: #ff0000">Sửa thông tin sản phẩm </h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', admin_product_path(@product)%> |
<%= link_to 'Trở lại', admin_products_path %>

app/views/admin/products/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Trang chủ</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" <%= link_to "Sản Phẩm ",admin_products_path%></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" <%= link_to "Loại sản phẩm ",admin_categories_path%></a>
      </li>
      <li class="nav-item">
        <a class="nav-link"<%= link_to "Tài khoản người dùng",admin_users_path%></a>
      </li>
        <li class="nav-item">
        <a class="nav-link" <%= link_to "Bài Đăng",admin_posts_path%></a>
      </li>
       <li class="nav-item">
        <a class="nav-link" <%= link_to "Bình luận",admin_comments_path%></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" <%= link_to "Trả lời bình luận",admin_replies_path %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link"<%= link_to('Đăng xuất', destroy_admin_user_session_path, method: :delete ,data:{ confirm:'Are you sure?'})%> </a>
      </li>
    </ul>
          <%= form_tag(admin_products_path, :method => "get",   
          class: 'navbar-form navbar-left') do %>  
             <div class="input-group">  
              <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>  
            <div class="input-group-btn" style="margin-right: 10%; height: 20%; width: 20%">  
              <%= button_tag "Search", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>  
          </div>  
  </div>  
<% end %>
  </div>
</nav>
</br></br>
<th class="new_product"><%= link_to 'Sản phẩm mới', admin_new_products_path %></th>
	<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">Id sản phẩm </th>
      <th scope="col">Tên sản phẩm</th>
      <th scope="col">Giá</th>
      <th scope="col">Mô tả</th>
      <th scope="col">Loại sản phẩm</th>
      <th scope="col">Hình ảnh </th>
    </tr>
  </thead>
  <tbody>
  	<% @products.each do |product| %>
    <tr>
      <td><%= product.id %></td>
      <td><%= product.name%></td>
      <td><%= product.price%></td>
      <td><%= product.description%></td>
      <td><%= product.category.name%></td>
      <td><%= product.image%></td>
      <td><%= link_to'Xóa', admin_destroy_products_path(product.id), method: :DELETE %></td>
      <td><%= link_to 'Sửa', admin_edit_products_path(product.id) %></td>
    </tr>
     <% end %>

  </tbody>
</table>
<nav aria-label="Page navigation example">
  <ul class="pagination">
    <li class="page-item">
      <a class="page-link" href="#" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    <li class="page-item"><a class="page-link" href="#">1</a></li>
    <li class="page-item"><a class="page-link" href="#">2</a></li>
    <li class="page-item"><a class="page-link" href="#">3</a></li>
    <li class="page-item">
      <a class="page-link" href="#" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
</nav>

app/views/admin/products/new.html.erb
<h1 style="margin-left: 20%; margin-right: 20%;color: #ff0000">Tạo sản phẩm mới</h1>
 <%= form_with(scope: :product, url: admin_create_products_path, local: true) do |form| %>

   <% if @product.errors.any? %>
     <div id="error_explanation">
       <h2><%= pluralize(@product.errors.count, "error") %> prohibited this @product from being saved:</h2>

       <ul>
       <% @product.errors.full_messages.each do |message| %>
         <li><%= message %></li>
       <% end %>
       </ul>
     </div>
   <% end %>

   <div class="form-group" style="margin-left: 20%; margin-right: 20%">
     <%= form.label :name %>
     <%= form.text_field :product_name, id: :product_name, class:'form-control'%>
   </div>

   <div class="form-group" style="margin-left: 20%; margin-right: 20%">
     <%= form.label :price %>
     <%= form.text_area :price, id: :product_price,  class:'form-control'%>
   </div>
    <div class="form-group" style="margin-left: 20%; margin-right: 20%" >
     <%= form.label :description %>
     <%= form.text_area :description, id: :product_description, class:'form-control' %>
   </div>
   <div class="form-group" style="margin-left: 20%; margin-right: 20%">
     <%= form.label :category_id %>
     <%= form.select(:category_id, @categories.map{|f| [f.name, f.id]}, {}, { :class => 'form-control' })%>
   </div>

   <div class="form-group" style="margin-left: 20%; margin-right: 20%">
     <%= form.label :image %>
     <%= form.file_field :image, id: :product_image,  class:'form-control'%>
   </div>

   <div class="actions" style="margin-left: 20%; margin-right: 20%">
     <%= form.submit %>
   </div>
 <% end %>

<%= link_to 'Trở lại', admin_products_path %>